#!/bin/bash
set -e

UDEV_RULE_FILE="/run/udev/rules.d/99-be-iis-generated-serial.rules"

add_uart_udev_rules() {
    local instance="$1"
    local i2c_bus="$2"
    local i2c_addr="$3"

    local instance_lc
    instance_lc="$(echo "$instance" | tr '[:upper:]' '[:lower:]')"

    echo "BE-IIS Adding udev rules for UART HAT instance $instance"

    cat >> "$UDEV_RULE_FILE" <<EOF

# BE-IIS HPP UART instance $instance
SUBSYSTEM=="tty", KERNEL=="ttySC*", DEVPATH=="*/i2c-${i2c_bus}/${i2c_bus}-${i2c_addr}/${i2c_bus}-${i2c_addr}:0/${i2c_bus}-${i2c_addr}:0.0/tty/ttySC*", SYMLINK+="beiis-uart-${instance_lc}-a"
SUBSYSTEM=="tty", KERNEL=="ttySC*", DEVPATH=="*/i2c-${i2c_bus}/${i2c_bus}-${i2c_addr}/${i2c_bus}-${i2c_addr}:0/${i2c_bus}-${i2c_addr}:0.1/tty/ttySC*", SYMLINK+="beiis-uart-${instance_lc}-b"
EOF
}

add_modbus_udev_rules() {
    local instance="$1"
    local i2c_bus="$2"
    local i2c_addr="$3"

    local instance_lc
    instance_lc="$(echo "$instance" | tr '[:upper:]' '[:lower:]')"

    echo "BE-IIS Adding udev rules for MODBUS HAT instance $instance"

    cat >> "$UDEV_RULE_FILE" <<EOF

# BE-IIS HPP MODBUS instance $instance
SUBSYSTEM=="tty", KERNEL=="ttySC*", DEVPATH=="*/i2c-${i2c_bus}/${i2c_bus}-${i2c_addr}/${i2c_bus}-${i2c_addr}:0/${i2c_bus}-${i2c_addr}:0.0/tty/ttySC*", SYMLINK+="beiis-modbus-${instance_lc}-a"
SUBSYSTEM=="tty", KERNEL=="ttySC*", DEVPATH=="*/i2c-${i2c_bus}/${i2c_bus}-${i2c_addr}/${i2c_bus}-${i2c_addr}:0/${i2c_bus}-${i2c_addr}:0.1/tty/ttySC*", SYMLINK+="beiis-modbus-${instance_lc}-b"
EOF
}

get_sc16is7xx_i2c_addr_from_overlay() {
    local overlay="$1"

    case "$overlay" in
        BE-IIS-HPP-UART-I|BE-IIS-HPP-MODBUS-I)
            echo "004c"
            ;;
        BE-IIS-HPP-UART-II|BE-IIS-HPP-MODBUS-II)
            echo "0049"
            ;;
        BE-IIS-HPP-UART-III|BE-IIS-HPP-MODBUS-III)
            echo "0048"
            ;;
        *)
            echo ""
            ;;
    esac
}

find_i2c_bus_for_addr() {
    local i2c_addr="$1"
    local dev

    dev="$(find /sys/bus/i2c/devices -maxdepth 1 -name "*-${i2c_addr}" | head -n 1)"

    if [ -n "$dev" ]; then
        basename "$dev" | cut -d- -f1
    else
        echo ""
    fi
}

declare -A INSTANCE_MAP=(
    ["0-0050"]="I"
    ["0-0060"]="II"
    ["0-0070"]="III"
    ["0-0074"]="IV"
    ["0-0076"]="V"
)

echo "BE-IIS Generating serial udev rules..."

mkdir -p /run/udev/rules.d

cat > "$UDEV_RULE_FILE" <<'EOF'
# BE-IIS generated serial udev rules
# Generated at boot. Not persistent.
#
# Do not edit this file manually.
EOF

for eep in \
    /sys/bus/i2c/devices/0-0050/eeprom \
    /sys/bus/i2c/devices/0-0060/eeprom \
    /sys/bus/i2c/devices/0-0070/eeprom \
    /sys/bus/i2c/devices/0-0074/eeprom \
    /sys/bus/i2c/devices/0-0076/eeprom
do
    if [ ! -e "$eep" ]; then
        continue
    fi

    addr="$(basename "$(dirname "$eep")")"
    inst="${INSTANCE_MAP[$addr]}"

    if [ -z "$inst" ]; then
        echo "BE-IIS Unknown EEPROM instance address: $addr"
        continue
    fi

    overlay="$(eepdump "$eep" 2>/dev/null | awk -F'"' '/^dt_blob /{print $2}')"

    case "$overlay" in
        BE-IIS-HPP-UART*|BE-IIS-HPP-MODBUS*)
            sc16_addr="$(get_sc16is7xx_i2c_addr_from_overlay "$overlay")"

            if [ -z "$sc16_addr" ]; then
                echo "BE-IIS Instance $inst ($addr): No SC16IS7xx mapping for $overlay"
                continue
            fi

            sleep 0.2

            sc16_bus="$(find_i2c_bus_for_addr "$sc16_addr")"

            if [ -z "$sc16_bus" ]; then
                echo "BE-IIS Instance $inst ($addr): SC16IS7xx bus not found, using fallback i2c-1"
                sc16_bus="1"
            fi

            echo "BE-IIS Instance $inst ($addr): $overlay uses SC16IS7xx 0x$sc16_addr on i2c-$sc16_bus"

            case "$overlay" in
                BE-IIS-HPP-UART*)
                    add_uart_udev_rules "$inst" "$sc16_bus" "$sc16_addr"
                    ;;
                BE-IIS-HPP-MODBUS*)
                    add_modbus_udev_rules "$inst" "$sc16_bus" "$sc16_addr"
                    ;;
            esac
            ;;
    esac
done

echo "BE-IIS Reloading serial udev rules..."
udevadm control --reload-rules || true
udevadm trigger --subsystem-match=tty || true

echo "BE-IIS Serial udev rule generation complete."